BBBBBBB BBBBBBBBBBBBB
BBBB BBBBBBBBBBB
BBBB BBBB

BBBBBBB BBBBBBBBB
 X XXXX XXXXXX XXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXX XXXX XX XXXXXXXXXXX
 X XXXXXXXX XX XXXXXX XXX XXXX XXXXXXXX XX XXXXXX XXXXXXXXX XXXXXXXXXXXXX
 X XXXX XX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXX
 X XXX XXXX XXXXXXXX XXXXXXXX XXX XXXXXXXXXXXXXX XX XXXXXXXXX XXXXXXXXX
 X XXXXXXXX XXXXXXXX XXX XX XXX
 X
 X XXXXXXXXX XXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXX XX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
 X
 X XXXX XXXXXXX XX XXXX XXXXXXXXX XXX XXX XXXXXXXXXXXX XX XXXXXX XXXXXX
 X XX XXXXX XXX XXXXX XX XXX XXX XXXXXXX XXXXXX XXXXXXX XX XXXXXXXXX XX
 X XXX XXXX XXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXX X XX XXX XXXXXXXX XX
 X XXX XXXX XXXXXXX XXX XXXXX XXXXXXXX
 X
 X XXXX XXXXXXX XX XXXXXXXXXXX XX XXX XXXX XXXX XX XXXX XX XXXXXXX
 X XXX XXXXXXX XXX XXXXXXXXX XXXXXXX XXXX XXX XXXXXXX XXXXXXXX XX
 X XXXXXXXXXXXXXXX XX XXXXXXX XXX X XXXXXXXXXX XXXXXXXX  XXX XXX
 X XXX XXXXXXX XXXXXX XXXXXXX XXX XXXX XXXXXXXX
 X
 X X XXXX XX XXXX XXXXXXX X XXX XXXXXXX XXXXXX XXXXXXX X XX XXXXXXXXX
 X XX XXX XXXX XX XXX XXXXXX XXXX XX XXXX XXXXXXXX  XX XXXX
 X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
BBBBBBBBBB

BBBBB BBBBBBBBBB
  XXX XXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBXX gettext(u'Studies') XXXXXXXXX
  XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXX
BBBBBBBB
BBBBB BBBBBBB
  XXXX XXXXXXXXXXXXXXXXXXXX
    XXXX gettext(u'Internships Managment') XXXXX
  XXXXXX

  XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBXX gettext(u'H\xf4pitaux') XXXXXXXXX
          XXXXXXX gettext(u'This process helps tutors while scores encoding.') XXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBXX gettext(u'Etudiants') XXXXXXXXX
          XXXXXXX gettext(u'This process helps tutors while scores encoding.') XXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBXX gettext(u'Stages') XXXXXXXXX
          XXXXXXX gettext(u'This process helps tutors while scores encoding.') XXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBXX gettext(u'P\xe9riodes') XXXXXXXXX
          XXXXXXX gettext(u'This process helps tutors while scores encoding.') XXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBXX gettext(u'Ma\xeetre de Stages') XXXXXXXXX
          XXXXXXX gettext(u'This process helps tutors while scores encoding.') XXXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
BBBBBBBB
