BBBBBBB BBBBBBBBBBBBB
BBBB BBBBBBBBBBB
BBBB BBBB

BBBBBBB BBBBBBBBB
 X XXXX XXXXXX XXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXX XXXX XX XXXXXXXXXXX
 X XXXXXXXX XX XXXXXX XXX XXXX XXXXXXXX XX XXXXXX XXXXXXXXX XXXXXXXXXXXXX
 X XXXX XX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXX
 X XXX XXXX XXXXXXXX XXXXXXXX XXX XXXXXXXXXXXXXX XX XXXXXXXXX XXXXXXXXX
 X XXXXXXXX XXXXXXXX XXX XX XXX
 X
 X XXXXXXXXX XXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXX XX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
 X
 X XXXX XXXXXXX XX XXXX XXXXXXXXX XXX XXX XXXXXXXXXXXX XX XXXXXX XXXXXX
 X XX XXXXX XXX XXXXX XX XXX XXX XXXXXXX XXXXXX XXXXXXX XX XXXXXXXXX XX
 X XXX XXXX XXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXX X XX XXX XXXXXXXX XX
 X XXX XXXX XXXXXXX XXX XXXXX XXXXXXXX
 X
 X XXXX XXXXXXX XX XXXXXXXXXXX XX XXX XXXX XXXX XX XXXX XX XXXXXXX
 X XXX XXXXXXX XXX XXXXXXXXX XXXXXXX XXXX XXX XXXXXXX XXXXXXXX XX
 X XXXXXXXXXXXXXXX XX XXXXXXX XXX X XXXXXXXXXX XXXXXXXX  XXX XXX
 X XXX XXXXXXX XXXXXX XXXXXXX XXX XXXX XXXXXXXX
 X
 X X XXXX XX XXXX XXXXXXX X XXX XXXXXXX XXXXXX XXXXXXX X XX XXXXXXXXX
 X XX XXX XXXX XX XXX XXXXXX XXXX XX XXXX XXXXXXXX  XX XXXX
 X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
BBBBBBBBBB

BBBBB BBBBBBBBBB
  XXXXXX XXXXXXBBB BBBBBBBBBXX gettext(u'Studies') XXXXXXXXX
  XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXX
  XXX XXXXXXXXXXXXXXX gettext(u'Places') XXXXX
BBBBBBBB
BBBBB BBBBBBB
  XXXX XXXXXXXXXXXXXXXXXXXX
    XXXX gettext(u'Places') XXXXX
  XXXXXX

  XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XX XXXXXXX XXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
            XXXXXXX
              XXXX
                  XXXX gettext(u'Number') XXXXX
                  XXXX gettext(u'Name') XXXXX
                  XXXX gettext(u'Address') XXXXX
                  XXXX gettext(u'Postal Code') XXXXX
                  XXXX gettext(u'Town') XXXXX
                  XXXX gettext(u'Country') XXXXX
                  XXXX gettext(u'Url') XXXXX
              XXXXX
            XXXXXXXX
            XXXXXXX
              XXXX
                  XXXX

                  XXXXX
              XXXXX
            XXXXXXXX
        XXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
BBBBBBBB
